apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  type: NodePort
  ports:
    - name: php-apache
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    component: php-apache