apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - name: nginx
        image: aylinaroche/nginx
        ports:
        - containerPort: 80