apiVersion: v1
kind: Service
metadata:
  name: client-service-nginx
spec:
  type: NodePort
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      nodePort: 31517
  selector:
    component: nginx