apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: proxy
  template:
    metadata:
      labels:
        component: proxy
    spec:
      containers:
      - name: proxy
        image: aylinaroche/proxy
        ports:
         - containerPort: 8081
