apiVersion: v1
kind: Service
metadata:
  name: client-service-flask
spec:
  type: NodePort
  ports:
    - name: flask
      port: 5000
      targetPort: 5000
      nodePort: 31516
  selector:
    component: flask