apiVersion: v1
kind: Service
metadata:
  name: client-service-proxy
spec:
  type: NodePort
  ports:
    - name: proxy
      port: 8081
      targetPort: 8081
      nodePort: 31515
  selector:
    component: proxy