apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: aylinaroche/myflask
        ports:
        - containerPort: 5000